### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/presentaciones-todos#10]
Crear el capítulo de Canvas

**Comment by DanielRamosAcosta** [comment]
Esto en teoría está listo, no @alu0100406122?

**Comment by alu0100406122** [comment]
Si, en principio si. Si no encuentro ninguna errata en el libro está todo correcto.

Gracias! ;)

**Comment by ericsuarez** [comment]
La presentación estuvo que te canvas :D

**Comment by DanielRamosAcosta** [comment]
Dios que malo jajajaja
