### ISSUE TITLE
gulp serve

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-SYTW-1617/presentaciones-todos#2]
Problemas iniciales con `gulp serve`

**Comment by crguezl** [comment]
Se puede ejecutar así: `node node_modules/gulp/bin/gulp.js serve`

**Comment by DanielRamosAcosta** [comment]
Y con `npm run serve` no funciona? Se supone que npm tiene que llamar al gulp que está instalado en `node_modules/.bin/gulp`, que a su vez apunta a `node_modules/gulp/bin/gulp.js`

**Comment by DanielRamosAcosta** [comment]
De todas maneras, el servidor que abre gitbook tiene errores a la hora de refrescar el servidor: GitbookIO/gitbook#1309, GitbookIO/gitbook#1379. Puede ser eso @crguezl?

**Comment by crguezl** [comment]
Puede ser. Lo cierto es que parece estar arreglado después que me bajara tu última versión 👍
