### ISSUE TITLE
Polymer

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/presentaciones-todos#20]
Crear el capítulo de Polymer

**Comment by DanielRamosAcosta** [comment]
@alu0100505078 no pasaste el `npm run lint`, socorro estoy convulsionando que alguien me ayude :skull:

**Comment by PedroRamosRguez** [comment]
@DanielRamosAcosta  uppsss 😇

**Comment by PedroRamosRguez** [comment]
Presentación realizada con éxito!!
