### ISSUE TITLE
React

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/presentaciones-todos#21]
Crear el capítulo de React

**Comment by crguezl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [tengo que poner el examen y las preguntas](https://trello.com/c/6L0JshhN/1-tengo-que-poner-el-examen-y-las-preguntas)

**Comment by crguezl** [comment]
@alu0100785265  mira este repo https://github.com/sokartema/ReactJS

Te puede ser útil para la elaboración de la presentación. Creo que Jazer (@sokartema) estará encantado de ayudar con las dudas que tengas.

**Comment by sokartema** [comment]
Si claro, si hay alguna duda podeis preguntarme. Por ahora solo he hecho una especie de formulario paso a paso. @crguezl Un saludo 👍
