### ISSUE TITLE
Dependencia

### ISSUE THREAD

**Issue by alu0100406122** [ULL-ESIT-SYTW-1617/presentaciones-todos#29]
Hola Daniel!! 
He seguido los siguientes pasos:
- Fork del repositorio.
- Rama con mi nombre.
- npm install --> Al hacer esto me devuelve un error con un paquete que no encuentra, concretamente "through2".

Lo he instalado manualmente y ya he podido hacer el npm install correctamente.

**Comment by DanielRamosAcosta** [comment]
Si es verdad, falta en el `package.json`, garcias!
