### ISSUE TITLE
Babel ES6, ES7 y ES8

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-SYTW-1617/presentaciones-todos#5]
Escribir capítulo y presentación por @DanielRamosAcosta  [babel-es6-es7-y-es8](https://github.com/ULL-ESIT-SYTW-1617/PresentacionESX_STYW)

**Comment by crguezl** [comment]
Issue abierto simplemente para el management del project "[presentaciones](https://github.com/ULL-ESIT-SYTW-1617/presentaciones-todos/projects/1?fullscreen=true)"

**Comment by DanielRamosAcosta** [comment]
Listo 👍
